export const courseData = [
    { "courseName": "Bachelor of Hospitality & Tourism Management" },
    { "courseName": "Bachelor of Business Administration" },
    { "courseName": "Post Baccalaureate Diploma in Business Management" },
    { "courseName": "Post Baccalaureate Diploma in Supply Chain Management" },
    { "courseName": "Post Baccalaureate Diploma in Business Analytics" },
    { "courseName": "Post Baccalaureate Diploma in Health Care Management" },
    { "courseName": "Post Baccalaureate Diploma in Occupational Health & Safety Management" },
    { "courseName": "Master of Business Administration - Community Economic Development" },
    { "courseName": "BET (Advance Standing) Post Degree - Petroleum" },
    { "courseName": "BET (Advance Standing) Post Degree - Electronics & Controls" },
    { "courseName": "BET (Advance Standing) Post Degree - Environmental Studies" },
    { "courseName": "Bachelor of Science" },
    { "courseName": "Bachelor of Health Sciences (Public Health)" },
    { "courseName": "Bachelor of Health Sciences (Public Health) - Accelerated Post Diploma/Degree - Public Health" },
    { "courseName": "Bachelor of Science in Human Nutrition" },
    { "courseName": "Bachelor of Science in Nursing" },
    { "courseName": "Diploma in Government Management" },
    { "courseName": "Advanced Manufacturing Management - PAMFM (1 Year)" },
    { "courseName": "Animal Care - PANCR (1 Year)" },
    { "courseName": "Business - Accounting - PBUSA (2 Years)" },
    { "courseName": "Business - Finance - PBUFI (2 Years)" },
    { "courseName": "Business - Human Resources - PBUHR (2 Years)" },
    { "courseName": "Business - Marketing - PBUMK (2 Years)" },
    { "courseName": "Business - PBUSS (2 Years)" },
    { "courseName": "Business Administration - Accounting - PBSAA (3 Years)" },
    { "courseName": "Business Administration - Finance - PBAFI (3 Years)" },
    { "courseName": "Business Administration - Human Resources - PBAHR (3 Years)" },
    { "courseName": "Business Administration - Marketing - PBAMK (3 Years)" },
    { "courseName": "Chemical Engineering Technology - PCETY (3 Years)" },
    { "courseName": "Chemical Engineering Technology Environmental - PCETE (3 Years)" },
    { "courseName": "Chemical Laboratory Technician - PCLTN (2 Years)" },
    { "courseName": "Child and Youth Care - PCYCD (3 Years)" },
    { "courseName": "Cloud Security - PCLSE (1 Year)" },
    { "courseName": "Community and Justice Services - PCAJS (2 Years)" },
    { "courseName": "Computer Engineering Technician - PCPEN (2 Years)" },
    { "courseName": "Computer Engineering Technology - PCPET (3 Years)" },
    { "courseName": "Computer Programming - PCPRG (2 Years)" },
    { "courseName": "Computer Systems Technician - Information Technology Infrastructure and Services Co-op - PSITC (2 Years)" },
    { "courseName": "Computer Systems Technician - Cyber Security - PCSCL (2 Years)" },
    { "courseName": "Computer Systems Technology - Software Development and Network Engineering Coop - PCSSC (3 Years)" },
    { "courseName": "Computer Systems Technology: Information Systems Engineering Co-op - PSISC (3 Years)" },
    { "courseName": "Early Childhood Education - PECED (2 Years)" },
    { "courseName": "Electrical Engineering Technician - PETEN (2 Years)" },
    { "courseName": "Electrical Techniques - PETEQ (1 Year)" },
    { "courseName": "Electromechanical Engineering Technician - PELTN (2 Years)" },
    { "courseName": "Electromechanical Engineering Technology - PEMTY (3 Years)" },
    { "courseName": "Environmental Control - PENCT (1 Year)" },
    { "courseName": "Environmental Technician - PENST (2 Years)" },
    { "courseName": "Honours Bachelor of Information Sciences (Cyber Security) â€“ PBAIS (4 Years)" },
    { "courseName": "Internet Communications Technology Coop - PICTC (3 Years)" },
    { "courseName": "Internet of Things and Machine Intelligence - PIOTM (1 Year)" },
    { "courseName": "Mechanical Engineering Technician - PMETN (2 Years)" },
    { "courseName": "Mechanical Engineering Technician Drafting - PMETD (2 Years)" },
    { "courseName": "Mechanical Engineering Technology - PMETY (3 Years)" },
    { "courseName": "Mechanical Engineering Technology Design and Drafting - PMEDD (3 Years)" },
    { "courseName": "Mechanical Technician - Tool Making - PMTTM (2 Years)" },
    { "courseName": "Mechanical Techniques - Plumbing - PLUMB (1 Year)" },
    { "courseName": "Mechanical Techniques - CNC & Precision Machining (1 Year)" },
    { "courseName": "Paralegal - PARAL (2 Years)" },
    { "courseName": "Pharmacy Technician - PPHTO (2 Years)" },
    { "courseName": "Police Foundations - PPOLF (2 Years)" },
    { "courseName": "Practical Nursing - PPNSG (2 Years)" },
    { "courseName": "Pre-Health Sciences Pathway to Advanced Diplomas and Degrees - PPHSS (1 Year)" },
    { "courseName": "Quality Assurance Manufacturing and Management - PQUAS (1 Year)" },
    { "courseName": "Social Service Worker - Gerontology - PSSWG (2 Years)" },
    { "courseName": "Social Service Worker - PSSWK (2 Years)" },
    { "courseName": "Advertising - Account Management Coop - PADAC (1 Year)" },
    { "courseName": "Advertising and Marketing Communications - PADMK (2 Years)" },
    { "courseName": "Advertising and Marketing Communications Management - PAMCM (3 Years)" },
    { "courseName": "Architectural Technician - PATCN (2 Years)" },
    { "courseName": "Architectural Technology - PARTY (3 Years)" },
    { "courseName": "Business Analysis and Process Management - PBAPM (1 Year)" },
    { "courseName": "Creative Industries Management - PCRIM (1 Year)" },
    { "courseName": "General Arts and Science - PGASU (2 Years)" },
    { "courseName": "General Arts and Science University 1 Year - PGAUC (1 Year)" },
    { "courseName": "Honours Bachelor of Business Administration (Accounting) - PBACC (4 Years)" },
    { "courseName": "Honours Bachelor of Business Administration (Finance) - PBBAF (4 Years)" },
    { "courseName": "Honours Bachelor of Business Administration (Human Resources Management) - PBHRM (4 Years)" },
    { "courseName": "Honours Bachelor of Business Administration (Marketing Management) - PBBAM (4 Years)" },
    { "courseName": "Honours Bachelor of Business Administration (Supply Chain Management) - PBSCM (4 Years)" },
    { "courseName": "Human Resources Management Coop - PHRMC (1 Year)" },
    { "courseName": "Interior Decorating - PINDE (2 Years)" },
    { "courseName": "Marketing Management Coop - PMKMC (1 Year)" },
    { "courseName": "Office Administration - Executive - POFAE (2 Years)" },
    { "courseName": "Office Administration - Health Services - POAHS (2 Years)" },
    { "courseName": "Professional Accounting - PPACG (1 Year)" },
    { "courseName": "Professional Accounting Coop - PPACGC (1 Year)" },
    { "courseName": "Project Management - PPRJM (1 Year)" },
    { "courseName": "Urban Design - PURBN (1 Year)" },
    { "courseName": "Advanced Special Effects Makeup Prosthetics and Props - PASEM (1 Year)" },
    { "courseName": "Art Fundamentals - PARTF (1 Year)" },
    { "courseName": "Honours Bachelor of Computer Science (Mobile Computing) - PBACS (4 Years)" },
    { "courseName": "Honours Bachelor of Computer Science (Specialty in Cloud Computing) - PBCPCC (4 Years)" },
    { "courseName": "Honours Bachelor of Computer Science (Specialty in Data Analytics) - PBCPDA (4 Years)" },
    { "courseName": "Honours Bachelor of Computer Science (Specialty in Data Engineering) - PBCPDE (4 Years)" },
    { "courseName": "Honours Bachelor of Computer Science (Specialty in Game Engineering) - PBCPGE (4 Years)" },
    { "courseName": "Honours Bachelor of Computer Science (Specialty in Network Engineering) - PBCPNN (4 Years)" },
    { "courseName": "Makeup for Media and Creative Arts - PMMCA (2 Years)" },
    { "courseName": "Media Fundamentals - PMDAF (1 Year)" },
    { "courseName": "Public Relations - Corporate Communications - PPRCC (1 Year)" },
    { "courseName": "Business Certificate" },
    { "courseName": "Continuing Care Assistant" },
    { "courseName": "Early Childhood Education Diploma" },
    { "courseName": "Early Childhood Education Certificate" },
    { "courseName": "Global Business Management Post Graduate Certificate" },
    { "courseName": "Certificate in Adult Education" },
    { "courseName": "Leadership in Community-Based Education" },
    { "courseName": "Consecutive Admission to CCES and LCBE" },
    { "courseName": "Certificate in Outdoor Recreation" },
    { "courseName": "Certificate in Recreation and Leisure Studies" },
    { "courseName": "Certificate in Arts Management" },
    { "courseName": "Certificate in Canada's Cultural Context" },
    { "courseName": "Certificate in Choral/Vocal Music" },
    { "courseName": "Certificate in Digital Media" },
    { "courseName": "Certificate in Instrumental Music" },
    { "courseName": "Certificate in Digital Ethics" },
    { "courseName": "BA-Arts & Culture-School of Fine & Performing Arts" },
    { "courseName": "BA in Adult Education as a First Degree (Hons.)" },
    { "courseName": "Bachelor of Arts - Community Health Three Year" },
    { "courseName": "Bachelor of Arts in Applied Linguistics" },
    { "courseName": "BA in Adult Education - Subsequent Degree (Hons.)" },
    { "courseName": "Certificate in Canadian Culture and Diversity" },
    { "courseName": "Certificate in Public Policy and Administration" },
    { "courseName": "Bachelor of Arts - Critical Criminology" },
    { "courseName": "Bachelor of Science - Biophysics" },
    { "courseName": "Certificate in Language & Culture Proficiency" },
    { "courseName": "Cert in Language Proficiency for Native Speakers" },
    { "courseName": "Certificate in Arts & Culture Studies" },
    { "courseName": "Introductory Cert. in Ancient Greek & Latin Lang." },
    { "courseName": "Enhanced Cert. in Ancient Greek & Latin Language" },
    { "courseName": "Certificate in Business French and Translation" },
    { "courseName": "Bachelor of Computing and Business" },
    { "courseName": "Certificate in Women's and Gender Studies" },
    { "courseName": "Certificate in Education and Applied Theatre" },
    { "courseName": "Certificate-Teaching English-Second/Foreign Lang." },
    { "courseName": "Bachelor of Science - Biochemistry" },
    { "courseName": "Certificate in Labour Studies" },
    { "courseName": "Certificate in Public Law" },
    { "courseName": "Certificate in Grape & Wine Technology" },
    { "courseName": "Certificate in Studies in Rhetoric & Prof Writing" },
    { "courseName": "Bachelor of Arts - Child and Youth Studies" },
    { "courseName": "Bachelor of Business Economics" },
    { "courseName": "Bachelor of Arts - Economics" },
    { "courseName": "Bachelor of Science - Environmental Geosciences" },
    { "courseName": "Bachelor of Arts - English Language & Literature" },
    { "courseName": "BASc Earth & Planetary Science Communications" },
    { "courseName": "Bachelor of Arts in Educational Studies" },
    { "courseName": "Certificate in Ethics" },
    { "courseName": "Bachelor of Arts - Film Studies" },
    { "courseName": "BSc Data Science & Analytics - Financial Analytics" },
    { "courseName": "BA Forensic Psychology and Criminal Justice" },
    { "courseName": "Certificate in Film Studies" },
    { "courseName": "Bachelor of Science - Computer Science" },
    { "courseName": "Bachelor of Arts - Geography" },
    { "courseName": "Bachelor of Science - Mathematics & Statistics" },
    { "courseName": "Bachelor of Arts - History" },
    { "courseName": "Bachelor of Child Health" },
    { "courseName": "Certificate in Speech, Language & Hearing Sciences" },
    { "courseName": "Bachelor of Arts - General Humanities" },
    { "courseName": "Bachelor of Science - Sciences" },
    { "courseName": "Bachelor of Science - Biomedical Sciences" },
    { "courseName": "Bachelor of Science - Neuroscience" },
    { "courseName": "Bachelor of Arts - Interactive Arts and Science" },
    { "courseName": "Bachelor of Science - Biotechnology" },
    { "courseName": "BSc Math & Statistics - Accelerated Math Studies" },
    { "courseName": "Bachelor of Science - Chemistry" },
    { "courseName": "Bachelor of Science - Physics" },
    { "courseName": "Bachelor of Accounting" },
    { "courseName": "Bachelor of Arts - Canadian Studies" },
    { "courseName": "Bachelor of Arts - Modern Languages" },
    { "courseName": "Bachelor of Arts - Labour Studies" },
    { "courseName": "Bachelor of Music - School of Fine & Performing Arts" },
    { "courseName": "Bachelor of Arts with a Major in Music" },
    { "courseName": "BA - Medieval & Renaissance Studies" },
    { "courseName": "Bachelor of Engineering, Integrated Engineering" },
    { "courseName": "Bachelor of Science - Geography" },
    { "courseName": "Bachelor of Science - Oenology & Viticulture" },
    { "courseName": "Bachelor of Physical Education" },
    { "courseName": "Bachelor of Arts - Popular Culture" },
    { "courseName": "Bachelor of Arts - Philosophy" },
    { "courseName": "Bachelor of Kinesiology" },
    { "courseName": "Certificate in Pre-Law" },
    { "courseName": "Bachelor of Arts - Political Science" },
    { "courseName": "Bachelor of Public Health" },
    { "courseName": "Bachelor of Arts - Psychology" },
    { "courseName": "Bachelor of Arts - Classics" },
    { "courseName": "BA - Visual Arts" },
    { "courseName": "Bachelor of Science - Biological Sciences" },
    { "courseName": "BSc Data Science & Analytics - Computational Data Sci" },
    { "courseName": "Bachelor of Science in Medical Sciences" },
    { "courseName": "Bachelor of Science - Kinesiology" },
    { "courseName": "Bachelor of Sport Management" },
    { "courseName": "Bachelor of Arts - Sociology" },
    { "courseName": "BSc Psychology" },
    { "courseName": "Bachelor of Arts - Social Sciences" },
    { "courseName": "BA Dramatic Arts - School of Fine & Performing Arts" },
    { "courseName": "Bachelor of Tourism and Environment" },
    { "courseName": "Bachelor of Arts - Media and Communication Studies" },
    { "courseName": "Bachelor of Arts - Business Communication Studies" },
    { "courseName": "Bachelor of Recreation and Leisure Studies" },
    { "courseName": "Certificate in Creative Writing" },
    { "courseName": "Bachelor of Arts - Women's and Gender Studies" },
    { "courseName": "Bachelor of Science - Earth Sciences" },
    { "courseName": "Bachelor of Computing and Business - Co-op" },
    { "courseName": "Bachelor of Business Economics - Co-op" },
    { "courseName": "Bachelor of Arts - Economics - Co-op" },
    { "courseName": "BSc - Environmental Geosciences - Co-op" },
    { "courseName": "BSc Data Science & Analytics - Financial Analytics Co-op" },
    { "courseName": "Bachelor of Science - Computer Science - Co-op" },
    { "courseName": "Bachelor of Arts - Geography - Co-op" },
    { "courseName": "Bachelor of Science - Mathematics & Statistics Co-op" },
    { "courseName": "Bachelor of Science - Combined Math/Comp Sci - Co-op" },
    { "courseName": "Bachelor of Science - Chemistry - Co-op Program" },
    { "courseName": "Bachelor of Accounting - Co-op" },
    { "courseName": "Bachelor of Arts - Labour Studies - Co-op" },
    { "courseName": "Bachelor of Business Administration - Co-op" },
    { "courseName": "Bachelor of Engineering, Integrated Engineer - Co-op" },
    { "courseName": "Bachelor of Science - Geography - Co-Op" },
    { "courseName": "Bachelor of Science - Oenology & Viticulture - Co-op" },
    { "courseName": "Bachelor of Arts - Political Science - Co-op" },
    { "courseName": "Bachelor of Public Health - Co-op" },
    { "courseName": "Bachelor of Arts - Psychology - Co-op" },
    { "courseName": "BSc Data Sci & Analyt - Computational Data Sci - Co-op" },
    { "courseName": "BSc Psychology - Co-op" },
    { "courseName": "BA Dramatic Arts, Fine & Performing Arts" },
    { "courseName": "Bachelor of Arts - Tourism and Environment" },
    { "courseName": "MBA" },
    { "courseName": "Master of Education" },
    { "courseName": "African Studies (Global Development Studies B.A.) Specialization" },
    { "courseName": "Ancient Greek & Roman Studies (Honours Arts)" },
    { "courseName": "Anthropology (Honours Science)" },
    { "courseName": "Anthropology - Biological Anthropology (Honours Science)" },
    { "courseName": "Anthropology & Forensics (Honours Arts)" },
    { "courseName": "Anthropology & Forensics (Honours Science)" },
    { "courseName": "Archaeology (Honours Arts)" },
    { "courseName": "Archaeology - Environmental Archaeology (Honours Arts)" },
    { "courseName": "Archaeology (Honours Science)" },
    { "courseName": "Archaeology - Environmental Archaeology (Honours Science)" },
    { "courseName": "Archaeology - Mediterranean Archaeology" },
    { "courseName": "Arts (Honours Arts)" },
    { "courseName": "Bachelor of Arts & Science" },
    { "courseName": "Biochemistry & Molecular Biology (Honours Science)" },
    { "courseName": "Biology (Honours Science)" },
    { "courseName": "Biomedical Science (Honours Science)" },
    { "courseName": "Business Administration (BBA)" },
    { "courseName": "Business Administration (BBA) - Accounting" },
    { "courseName": "Business Administration (BBA) - Economics" },
    { "courseName": "Business Administration (BBA) - Entrepreneurship" },
    { "courseName": "Business Administration (BBA) - Ethics & Sustainability" },
    { "courseName": "Business Administration (BBA) - Finance" },
    { "courseName": "Business Administration (BBA) - Human Resources Management" },
    { "courseName": "Business Administration (BBA) - Information Systems & E-Commerce" },
    { "courseName": "Business Administration (BBA) - Marketing & Consumer Culture" },
    { "courseName": "Business Administration (BBA) - Niigaaniiwin The Art of Leading" },
    { "courseName": "Business & Arts (Honours Arts)" },
    { "courseName": "Business & Science (Honours Science)" },
    { "courseName": "Canadian Studies (Honours Arts)" },
    { "courseName": "Chemical Physics (Honours Science)" },
    { "courseName": "Chemistry (Honours Science)" },
    { "courseName": "Computer Science (Honours Science)" },
    { "courseName": "Computer Science - Computer Science (Honours Science)" },
    { "courseName": "Computer Science - Data Analytics (Honours Science)" },
    { "courseName": "Computer Science - Software Engineering (Honours Science)" },
    { "courseName": "Computing Systems & Business (Honours Arts)" },
    { "courseName": "Computing Systems & Economics (Honours Arts)" },
    { "courseName": "Computing Systems & Media Studies (Honours Arts)" },
    { "courseName": "Computer Science & Physics (Honours Science)" },
    { "courseName": "Cultural Studies (Honours Arts)" },
    { "courseName": "Cultural Studies & Business (Honours Arts)" },
    { "courseName": "Culture & Theory (Cultural Studies B.A.) Specialization" },
    { "courseName": "Economics (Honours Arts)" },
    { "courseName": "Economics (Honours Science)" },
    { "courseName": "Economics & Business (Honours Arts)" },
    { "courseName": "English & Business (Honours Arts)" },
    { "courseName": "English Literature (Honours Arts)" },
    { "courseName": "English Literature (Honours Arts) - Literary History" },
    { "courseName": "English Literature (Honours Arts) - Racial and Social Justice" },
    { "courseName": "Environmental & Resource Science (Honours Science)" },
    { "courseName": "Environmental & Resource Studies (Honours Arts)" },
    { "courseName": "Environmental & Resource Studies and Business (Honours Arts)" },
    { "courseName": "Environmental Chemistry (Honours Science)" },
    { "courseName": "Environmental Geoscience (Honours Science)" },
    { "courseName": "Environmental Science/Studies (Honours)" },
    { "courseName": "Environmental Science (Honours Science) - Climate Change Science & Policy" },
    { "courseName": "Environmental Studies (Honours Arts) - Climate Change Science & Policy" },
    { "courseName": "Film & Media (Cultural Studies B.A.) Specialization" },
    { "courseName": "Financial Science (B.Sc.)" },
    { "courseName": "Forensics & Arts (Honours Arts)" },
    { "courseName": "Forensics & Arts (Honours Arts) - Law & Policing Specialization" },
    { "courseName": "Forensics & Business (Honours Arts)" },
    { "courseName": "Forensics & Science (Honours Science)" },
    { "courseName": "Forensics & Science (Honours Science) - Law & Policing Specialization" },
    { "courseName": "French & Francophone Studies (Honours Arts)" },
    { "courseName": "French & Francophone Studies (Honours Arts) - French Writing" },
    { "courseName": "Gender & Social Justice (Honours Arts)" },
    { "courseName": "Gender & Social Justice (Honours Arts) - Feminist Studies" },
    { "courseName": "Gender & Social Justice B.A. (Honours Arts) - Sexuality Studies" },
    { "courseName": "Geography (Honours Arts)" },
    { "courseName": "Geography (Honours Arts) - Climate Change Science & Policy" },
    { "courseName": "Geography (Honours Science)" },
    { "courseName": "Geography (Honours Science) - Climate Change Science & Policy" },
    { "courseName": "Global Migration & Refugee Studies (Global Development Studies B.A.) Specialization" },
    { "courseName": "Greek & Latin (Ancient Greek & Roman Studies B.A.) Specialization" },
    { "courseName": "Health Sciences (Biology B.Sc.) Specialization" },
    { "courseName": "Health Studies (Sociology B.A.) Specialization" },
    { "courseName": "History (Honours Arts)" },
    { "courseName": "History & Business (Honours Arts)" },
    { "courseName": "Indigenous Environmental Science (Honours Science)" },
    { "courseName": "Indigenous Environmental Studies (Honours Arts)" },
    { "courseName": "Indigenous Studies (Honours Arts)" },
    { "courseName": "Indigenous Studies - Applied Indigenous Knowledge (Honours Arts) Specialization" },
    { "courseName": "Indigenous Studies - Indigenous Performance (Honours Arts) Specialization" },
    { "courseName": "Indigenous Studies - Nishinaabemowin (Honours Arts) Specialization" },
    { "courseName": "Indigenous Studies & Business (Honours Arts)" },
    { "courseName": "Information Systems (Honours Arts)" },
    { "courseName": "Information Systems & Business (Honours Arts)" },
    { "courseName": "Information Systems & Science (Honours Science)" },
    { "courseName": "Integrated Arts (Cultural Studies B.A.) Specialization" },
    { "courseName": "Global Development & Business (Honours Arts)" },
    { "courseName": "Global Development Studies (Honours Arts)" },
    { "courseName": "International Development Studies (Honours Arts) - Latin American Studies" },
    { "courseName": "International Political Economy (Honours Arts)" },
    { "courseName": "Literature & Narrative (Cultural Studies B.A.) Specialization" },
    { "courseName": "Mathematical Economics (Honours Science)" },
    { "courseName": "Mathematical Physics (Honours Science)" },
    { "courseName": "Mathematics (Honours Science)" },
    { "courseName": "Mathematics (Honours Science) - Statistics Specialization" },
    { "courseName": "Mathematics - Mathematical Finance (Honours Science)" },
    { "courseName": "Media Studies (Honours Arts)" },
    { "courseName": "Media Studies & Business (Honours Arts)" },
    { "courseName": "Philosophy (Honours Arts)" },
    { "courseName": "Philosophy - Ethics Specialization (Honours Arts)" },
    { "courseName": "Philosophy & Business (Honours Arts)" },
    { "courseName": "Physics (Honours Science)" },
    { "courseName": "Political Studies (Honours Arts)" },
    { "courseName": "Political Studies (Honours Arts) - Legal Studies Option" },
    { "courseName": "Political Studies - Public Policy (Honours Arts)" },
    { "courseName": "Political Studies & Business (Honours Arts)" },
    { "courseName": "Political Studies & Forensics (Honours Arts)" },
    { "courseName": "Political Studies B.A. (Honours Arts) - Political Theory" },
    { "courseName": "Political Studies B.A. (Honours Arts) - World Politics" },
    { "courseName": "Psychological Development (Honours Arts) Specialization" },
    { "courseName": "Psychological Development (Honours Science) Specialization" },
    { "courseName": "Psychology (Honours Arts)" },
    { "courseName": "Psychology (Honours Science)" },
    { "courseName": "Psychology (Honours Science) - Health & Well-being" },
    { "courseName": "Psychology & Business (Honours Arts)" },
    { "courseName": "Psychology & Business (Honours Science)" },
    { "courseName": "Psychology & Economics (Honours Arts)" },
    { "courseName": "Psychology & Forensics (Honours Arts)" },
{ "courseName": "Psychology & Forensics (Honours Science)" },
{ "courseName": "Quebec & Franco-Canadian Studies (French & Francophone Studies B.A.) Specialization" },
{ "courseName": "Science (Honours Science)" },
{ "courseName": "Social Work (BSW)" },
{ "courseName": "Sociology (Honours Arts)" },
{ "courseName": "Sociology - Social Justice & Equity Studies" },
{ "courseName": "Sociology - Socio-Legal Studies" },
{ "courseName": "Sociology & Business (Honours Arts)" },
{ "courseName": "Sustainable Agriculture & Food Systems (Honours Arts)" },
{ "courseName": "Sustainable Agriculture & Food Systems (Honours Arts) - Small-scale Farming" },
{ "courseName": "Sustainable Agriculture & Food Systems (Honours Science)" },
{ "courseName": "Sustainable Agriculture & Food Systems (Honours Science) - Small-scale Farming" },
{ "courseName": "Anthropology (Honours Arts)" },
{ "courseName": "Anthropology & Psychology (Honours Arts)" },
{ "courseName": "Anthropology & Sociology (Honours Arts)" },
{ "courseName": "Arts & Business (Honours Arts)" },
{ "courseName": "Business (BBA) - Communications Option" },
{ "courseName": "Child & Youth Studies (Honours Arts)" },
{ "courseName": "Child & Youth Studies and Psychology (Honours Arts)" },
{ "courseName": "Child & Youth Studies and Sociology (Honours Arts)" },
{ "courseName": "Communications (Honours Arts)" },
{ "courseName": "Communications - Business Communications" },
{ "courseName": "Communications - Media Relations" },
{ "courseName": "Computing Systems (General Arts)" },
{ "courseName": "Computer Science (General Science)" },
{ "courseName": "English Literature & Business (Honours Arts)" },
{ "courseName": "English Literature & Media Studies (Honours Arts)" },
{ "courseName": "English Literature & Psychology (Honours Arts)" },
{ "courseName": "English Literature & Sociology (Honours Arts)" },
{ "courseName": "Gender & Social Justice (General Arts)" },
{ "courseName": "Information Systems & Media Studies (Honours Arts)" },
{ "courseName": "Media Studies & Psychology (Honours Arts)" },
{ "courseName": "Philosophy (General Arts)" },
{ "courseName": "Policing & Community Well-Being" },
{ "courseName": "Psychology (Honours Arts) - Health & Well-being" },
{ "courseName": "Psychology (Honours Arts) - Psychological Development" },
{ "courseName": "Psychology (Honours Science) - Psychological Development" },
{ "courseName": "Psychology & Sociology (Honours Arts)" },
{ "courseName": "Science & Business (Honours Science)" },
{ "courseName": "Human Resource Management & Business Communication - Dual Post-Graduate Certificate (Durham)" },
{ "courseName": "Human Resources, Marketing & Entrepreneurship - Dual Post-Graduate Certificate (Durham)" },
{ "courseName": "Accounting - Post-Graduate Certificate" },
{ "courseName": "Finance - Post-Graduate Certificate" },
{ "courseName": "Human Resources, Marketing & Entrepreneurship - Dual Post-Graduate Certificate" },
{ "courseName": "Master of Management" },
{ "courseName": "Master of Management Strategic Change Management" },
{ "courseName": "3D Modelling and Visual Effects Production" },
{ "courseName": "Accounting, Bachelor of Commerce" },
{ "courseName": "Accounting, Business" },
{ "courseName": "Accounting, Business Administration" },
{ "courseName": "Accounting, Professional Practice" },
{ "courseName": "Addictions and Mental Health" },
{ "courseName": "Advertising & Graphic Design" },
{ "courseName": "Advertising - Media Management" },
{ "courseName": "Advertising and Marketing Communications" },
{ "courseName": "Alternative Dispute Resolution" },
{ "courseName": "Architectural Technology" },
{ "courseName": "Artificial Intelligence with Machine Learning" },
{ "courseName": "Baking and Pastry Arts Management" },
{ "courseName": "Biotechnology" },
{ "courseName": "Broadcast Television/Videography" },
{ "courseName": "Building Construction Technician" },
{ "courseName": "Business Administration" },
{ "courseName": "Business Insights and Analytics" },
{ "courseName": "Business Management" },
{ "courseName": "Carpentry and Renovation Technician" },
{ "courseName": "Carpentry and Renovation Techniques" },
{ "courseName": "Child and Youth Care" },
{ "courseName": "Civil Engineering Technology" },
{ "courseName": "Cloud Computing" },
{ "courseName": "Community and Justice Services" },
{ "courseName": "Computer Engineering Technology" },
{ "courseName": "Computer Programming" },
{ "courseName": "Computer Programming and Analysis" },
{ "courseName": "Computer Systems Technician – Information Technology Infrastructure and Services" },
{ "courseName": "Construction Engineering Technology" },
{ "courseName": "Content Strategy" },
{ "courseName": "Cosmetic Management" },
{ "courseName": "Culinary Management" },
{ "courseName": "Culinary Skills" },
{ "courseName": "Design Foundation" },
{ "courseName": "Digital Business Management, Bachelor of Commerce" },
{ "courseName": "Early Childhood Education" },
{ "courseName": "Electrical Engineering Technician - Control Systems" },
{ "courseName": "Electrical Engineering Technology - Control Systems" },
{ "courseName": "Electrical Techniques" },
{ "courseName": "Electromechanical Engineering Technician" },
{ "courseName": "Electromechanical Engineering Technology" },
{ "courseName": "Electronics Engineering Technician" },
{ "courseName": "Electronics Engineering Technology" },
{ "courseName": "Emergency Telecommunications" },
{ "courseName": "Enterprise Software Development" },
{ "courseName": "Entrepreneurial Enterprise, Business Management" },
{ "courseName": "Esthetician/Spa Management" },
{ "courseName": "Event Management" },
{ "courseName": "Fashion Arts and Business" },
{ "courseName": "Fashion Management" },
{ "courseName": "Fashion Management, Bachelor of Commerce" },
{ "courseName": "Finance, Bachelor of Commerce" },
{ "courseName": "Financial Planning" },
{ "courseName": "Financial Services, Business Management" },
{ "courseName": "Fitness and Health Promotion" },
{ "courseName": "Furniture and Cabinetmaking Techniques" },
{ "courseName": "Game Programming" },
{ "courseName": "General Arts and Science - Technology" },
{ "courseName": "Global Business Management" },
{ "courseName": "Graphic Design" },
{ "courseName": "Graphic Design for Print and Web" },
{ "courseName": "Healthcare Management, Bachelor of Commerce" },
{ "courseName": "Heating, Refrigeration and Air Conditioning Technician" },
{ "courseName": "Heating, Refrigeration and Air Conditioning Technology" },
{ "courseName": "Hospitality - Hotel and Restaurant Operations Management" },
{ "courseName": "Hospitality and Tourism Operations Management" },
{ "courseName": "Human Resources Management" },
{ "courseName": "Human Resources Management, Bachelor of Commerce" },
{ "courseName": "Industrial Woodworking Technician" },
{ "courseName": "Information Technology Solutions" },
{ "courseName": "Interior Decorating" },
{ "courseName": "International Business, Bachelor of Commerce" },
{ "courseName": "International Development" },
{ "courseName": "Law Clerk" },
{ "courseName": "Management Studies, Bachelor of Commerce" },
{ "courseName": "Marketing Management" },
{ "courseName": "Marketing, Bachelor of Commerce" },
{ "courseName": "Marketing, Business" },
{ "courseName": "Massage Therapy" },
{ "courseName": "Mechanical Engineering Technician" },
{ "courseName": "Mechanical Engineering Technology" },
{ "courseName": "Mechanical Techniques - Millwright" },
{ "courseName": "Media Communications" },
{ "courseName": "Multimedia Design and Development" },
{ "courseName": "Paralegal" },
{ "courseName": "Paralegal Education" },
{ "courseName": "Pharmacy Technician" },
{ "courseName": "Plumbing Techniques" },
{ "courseName": "Police Foundations" },
{ "courseName": "Practical Nursing" },
{ "courseName": "Professional Writing and Communications" },
{ "courseName": "Project Management" },
{ "courseName": "Protection, Security and Investigation" },
{ "courseName": "Public Relations (Graduate Certificate)" },
{ "courseName": "Regulatory Affairs" },
{ "courseName": "Research Analyst" },
{ "courseName": "Social Service Worker" },
{ "courseName": "Sport Management" },
{ "courseName": "Supply Chain Management" },
{ "courseName": "Supply Chain Management, Bachelor of Commerce" },
{ "courseName": "Tourism - Travel Services Management" },
{ "courseName": "User Experience (UX) Design" },
{ "courseName": "Virtual Production NEW" },
{ "courseName": "Web Design and Development" },
{ "courseName": "Web Development" },
{ "courseName": "Wireless Telecommunications" },
{ "courseName": "Associate of Arts Degree" },
{ "courseName": "Associate of Arts Degree - Creative Writing" },
{ "courseName": "Associate of Arts Degree - English" },
{ "courseName": "Associate of Arts Degree - Psychology" },
{ "courseName": "Bachelor of Arts with a Major in Interdisciplinary Studies" },
{ "courseName": "Bachelor of Arts with a Major in Psychology" },
{ "courseName": "Bachelor of Science - General" },
{ "courseName": "Associate of Science Degree" },
{ "courseName": "Associate of Science Degree - Biology" },
{ "courseName": "Bachelor of Business Administration Degree" },
{ "courseName": "Business Administration Diploma" },
{ "courseName": "Business Administration Certificate" },
{ "courseName": "Communication Studies Diploma" },
{ "courseName": "Bachelor of Communication Studies Degree" },
{ "courseName": "North American Business Management Applied Post-Baccalaureate Diploma" },
{ "courseName": "North American Business Management Post-Baccalaureate Diploma" },
{ "courseName": "Bachelor of Tourism Management Degree" },
{ "courseName": "Tourism Management Co-operative Education Diploma" },
{ "courseName": "Diploma in Tourism Management International" },
{ "courseName": "Global Hospitality and Tourism Management Post - Post-Baccalaureate Diploma" },
{ "courseName": "Automotive Collision and Refinishing Diploma" },
{ "courseName": "Automotive Service Technology Diploma" },
{ "courseName": "Heavy Mechanical Technology" },
{ "courseName": "Automotive Parts and Service Management" },
{ "courseName": "Accounting Diploma" },
{ "courseName": "Cosmetology Diploma" },
{ "courseName": "Culinary Art Diploma" },
{ "courseName": "CAD & BIM Technology Diploma" },
{ "courseName": "Computer System Technology Diploma" },
{ "courseName": "Dental Technology Science Diploma" },
{ "courseName": "Electronics Repair Technology Diploma" },
{ "courseName": "Early Childhood Care and Education Diploma" },
{ "courseName": "Marketing Technology Diploma" },
{ "courseName": "Optician Diploma" },
{ "courseName": "Health Care Assistant" },
{ "courseName": "Hospitality Management Diploma" },
{ "courseName": "Occupational and Physical Therapy Assistant Diploma" },
{ "courseName": "Music Diploma" },
{ "courseName": "Dance Diploma" },
{ "courseName": "Fashion Design and Production Diploma" },
{ "courseName": "Graphic Designing Diploma" },
{ "courseName": "Jewellery Art and Design Diploma" },
{ "courseName": "PG Diploma Business and Project Management" },
{ "courseName": "PG Diploma Business Management" },
{ "courseName": "Post Graduate Diploma in Hospitality Management" },
{ "courseName": "PG Diploma in Network Technology Administration & Security" },
{ "courseName": "PG Diploma in Cybersecurity" },
{ "courseName": "University Transfer- Arts" },
{ "courseName": "University Transfer- Science" },
{ "courseName": "University Transfer- Computing Science" },
{ "courseName": "University Transfer- Engineering" },
{ "courseName": "Associate of Science- Computer Science Pathway" },
{ "courseName": "Bachelor of Applied Music" },
{ "courseName": "Bachelor of Hospitality Management" },
{ "courseName": "Administrative Professional" },
{ "courseName": "Artisan Baking Certificate" },
{ "courseName": "Asian Culinary Certificate" },
{ "courseName": "Baking and Pastry Arts - Artisan Baking & Pastry Dual Certificates" },
{ "courseName": "Esthetics & Spa Therapy" },
{ "courseName": "Hairstylist Certificate" },
{ "courseName": "Legal Administration Assistant Certificate" },
{ "courseName": "Medical Office Assistant" },
{ "courseName": "Medical Transcriptionist" },
{ "courseName": "3D Computer Animation" },
{ "courseName": "Advanced CNC Manufacturing" },
{ "courseName": "Agri-Business Management" },
{ "courseName": "Animation" },
{ "courseName": "Applied Artificial Intelligence & Machine Learning (Optional Co-op)" },
{ "courseName": "Applied Electrical Motion and Control Management" },
{ "courseName": "Applied Electrical Motion and Control Management - Automotive" },
{ "courseName": "Applied Electrical Motion and Control Management - Logistical Automation" },
{ "courseName": "Applied Energy Management" },
{ "courseName": "Applied Energy Management- Renewable Energy" },
{ "courseName": "Applied Energy Management - Energy Systems Control" },
{ "courseName": "Applied Energy Management - Residential & Commercial" },
{ "courseName": "Applied Manufacturing Management - Automation" },
{ "courseName": "Applied Manufacturing Management - Design Integration - Aerospace Stream" },
{ "courseName": "Applied Manufacturing Management - Design Integration - Electronics Manufacturing" },
{ "courseName": "3D Computer Animation" },
{ "courseName": "Applied Manufacturing Management - Design Integration 3D Printing" },
{ "courseName": "Applied Manufacturing Management - Design Integration- Aerospace Stream" },
{ "courseName": "Applied Manufacturing Management - Machining" },
{ "courseName": "Applied Manufacturing Management - Welding" },
{ "courseName": "Applied Network Infrastructure and System Administration" },
{ "courseName": "Applied Research" },
{ "courseName": "Bachelor of Applied Biotechnology (Honours)" },
{ "courseName": "Bachelor of Business Administration (Honours)- Accounting, Audit and Information Technology" },
{ "courseName": "Bachelor of Business Administration (Honours)- International Business Management" },
{ "courseName": "Bachelor of Computer Science" },
{ "courseName": "Bachelor of Computer Science (Honours)" },
{ "courseName": "Bachelor of Applied Health Information Science" },
{ "courseName": "Bachelor of Applied Technology (Honours) - Architecture - Project and Facility Management" },
{ "courseName": "Bachelor of Commerce (Honours) Financial Services" },
{ "courseName": "Bachelor of Communication Management" },
{ "courseName": "Bachelor of Community and Criminal Justice" },
{ "courseName": "Bachelor of Design (Honours)" },
{ "courseName": "Bachelor of Early Learning Program Development" },
{ "courseName": "Bachelor of Engineering - Building Systems Engineering" },
{ "courseName": "Bachelor of Engineering - Power Systems Engineering" },
{ "courseName": "Bachelor of Engineering - Sustainable Design Engineering" },
{ "courseName": "Bachelor of Engineering - Power System Engineering" },
{ "courseName": "Bachelor of Engineering - Mechanical System Engineering" },
{ "courseName": "Bachelor of Engineering - Cyber System Engineering" },
{ "courseName": "Bachelor of Environmental Public Health (Honours)" },
{ "courseName": "Bachelor of Human Resource Management" },
{ "courseName": "Bachelor of Interior Design (Honours)" },
{ "courseName": "Baking and Pastry Arts" },
{ "courseName": "Big Data Solution Architecture (Optional Co-op)" },
{ "courseName": "Biotechnology Technician Fast Track" },
{ "courseName": "Bookkeeping" },
{ "courseName": "Broadcasting - Television and Independent Production" },
{ "courseName": "Broadcasting Performance and Digital Media" },
{ "courseName": "Business" },
{ "courseName": "Business - Finance" },
{ "courseName": "Business - Insurance" },
{ "courseName": "Business - International Business" },
{ "courseName": "Business - Marketing" },
{ "courseName": "Business - Purchasing" },
{ "courseName": "Business - Supply Chain and Operations for Commercial Trucking" },
{ "courseName": "Business Administration - Accounting" },
{ "courseName": "Business Administration - Financial Planning" },
{ "courseName": "Business Administration - Management" },
{ "courseName": "Business Administration - Marketing" },
{ "courseName": "Business Analytics" },
{ "courseName": "Business Development and Sales" },
{ "courseName": "Broadcast - Radio" },
{ "courseName": "Career Development Professional" },
{ "courseName": "Clinical Research" },
{ "courseName": "Charcuterie and Artisanal Foods" },
{ "courseName": "Civil Engineering Technician" },
{ "courseName": "Climate Change Mitigation" },
{ "courseName": "Cloud Data Management" },
{ "courseName": "Cloud Development and Operations" },
{ "courseName": "Community Settlement Services" },
{ "courseName": "Community Pharmacy Assistant" },
{ "courseName": "Computer Animation & Motion Graphics" },
{ "courseName": "Computer Applications Development (Optional Co-op)" },
{ "courseName": "Computer System Technician - Informative Technology Infrastructure and Services" },
{ "courseName": "Computer-Aided Drafting & Design" },
{ "courseName": "Construction Management" },
{ "courseName": "Computer Application Security" },
{ "courseName": "Construction Engineering Technology - Architecture" },
{ "courseName": "Construction Techniques - Brick and Stone" },
{ "courseName": "Construction Techniques (Welding, HVAC, Plumbing and Masonry)" },
{ "courseName": "Cybersecurity Response Planning" },
{ "courseName": "Data Processing and Reporting" },
{ "courseName": "Design Foundations" },
{ "courseName": "Design Solution Management" },
{ "courseName": "Digital Solutions Management (Optional Co-op)" },
{ "courseName": "Drafting and Design for Additive Manufacturing" },
{ "courseName": "Educational Support" },
{ "courseName": "Electrical Engineering Technician" },
{ "courseName": "Electrical Engineering Technician - Industrial" },
{ "courseName": "Enhanced Practice for Internationally Educated Nurses" },
{ "courseName": "Esthetician" },
{ "courseName": "Electro Mechanical and Automation Maintenance" },
{ "courseName": "Embedded Systems Development" },
{ "courseName": "Energy Systems Engineering Technology - Electrical" },
{ "courseName": "English for Academic Studies" },
{ "courseName": "Environmental Building Sciences" },
{ "courseName": "Environmental Engineering Applications" },
{ "courseName": "Esports Marketing and Event Management" },
{ "courseName": "Esports and Event Media Production" },
{ "courseName": "Financial Planning Services" },
{ "courseName": "Financial Technology" },
{ "courseName": "Fitness Health Promotion" },
{ "courseName": "Food Processing Technician" },
{ "courseName": "Food Safety Quality Assurance - Food Processing" },
{ "courseName": "Food and Beverage Management - Hotel and Restaurant Operations" },
{ "courseName": "Fraud Investigation and Risk Management" },
{ "courseName": "Game - Design" },
{ "courseName": "Game - Art" },
{ "courseName": "General Arts and Science - Diploma Option" },
{ "courseName": "General Arts and Science - One Year" },
{ "courseName": "Global Hospitality Management" },
{ "courseName": "Global Public Health Management" },
{ "courseName": "Health Care Administration and Service Management" },
{ "courseName": "Health Care Administration Management (Nursing Leadership Stream)" },
{ "courseName": "Health Care Quality Improvement and Safety Management" },
{ "courseName": "Health Office Administration" },
{ "courseName": "Health and Social Systems Navigation" },
{ "courseName": "Healthcare Project Leadership and Management" },
{ "courseName": "Hospitality Operations - Food and Beverage" },
{ "courseName": "Human Factors and Ergonomics" },
{ "courseName": "Human Resource Management" },
{ "courseName": "Human Service Foundation" },
{ "courseName": "IT Innovation and Design" },
{ "courseName": "Information Technology Business Analysis" },
{ "courseName": "Information Technology Network Security" },
{ "courseName": "Information Technology Project Management" },
{ "courseName": "Interactive Media Management - Interaction Design" },
{ "courseName": "Journalism" },
{ "courseName": "Laboratory Quality Management" },
{ "courseName": "Long Term Care and Retirement Community Management" },
{ "courseName": "Machining for Manufacturing" },
{ "courseName": "Management and Leadership Development" },
{ "courseName": "Management in Community Services" },
{ "courseName": "Manufacturing Engineering Technology - Welding and Robotics" },
{ "courseName": "Mechanical Engineering Technician - Automated Manufacturing" },
{ "courseName": "Mechanical Engineering Technology - Automated Manufacturing" },
{ "courseName": "Mechanical Engineering Technology - Design and Analysis" },
{ "courseName": "Mechanical Engineering Technology - Robotics and Automation" },
{ "courseName": "Mechanical Technician - CNC" },
{ "courseName": "Media Foundations" },
{ "courseName": "Medical Office Practices" },
{ "courseName": "Mental Health and Substance Use" },
{ "courseName": "Mobile Solutions Development (Optional Co-op)" },
{ "courseName": "Mobile and Web Development" },
{ "courseName": "Motive Power Fundamentals - Automotive Repair" },
{ "courseName": "Motive Power Technician - Automotive Service" },
{ "courseName": "Motive Power Technician - Heavy Duty Equipment" },
{ "courseName": "Motive Power Technician - Truck and Coach" },
{ "courseName": "Nursing Leadership and Healthcare Management" },
{ "courseName": "Nutrition and Food Services Management" },
{ "courseName": "Occupational Health, Safety and Wellness" },
{ "courseName": "Office Administration - Executive" },
{ "courseName": "Office Administration - Legal" },
{ "courseName": "Packaging Engineering Technician" },
{ "courseName": "Payroll and Bookkeeping" },
{ "courseName": "Pre-Health Sciences Pathway to Certificates and Diplomas" },
{ "courseName": "Pre-Service Firefighter Education and Training" },
{ "courseName": "Predictive Analytics" },
{ "courseName": "Process Quality Engineering" },
{ "courseName": "Public Relations" },
{ "courseName": "Quality Assurance - Manufacturing and Management" },
{ "courseName": "Renewable Energy Techniques" },
{ "courseName": "Reporting Systems and Database Development" },
{ "courseName": "Robotics and Industrial Automation" },
{ "courseName": "Social Media Marketing" },
{ "courseName": "Software Engineering Technician" },
{ "courseName": "Software Engineering Technology" },
{ "courseName": "Software Quality Assurance and Test Engineering (Optional Co-op)" },
{ "courseName": "Strategic Global Business Management" },
{ "courseName": "Strategic Marketing Communication" },
{ "courseName": "Strategic Marketing and Research Analysis" },
{ "courseName": "Structural Packaging Design and Management" },
{ "courseName": "Structural Steel Management and Detailing" },
{ "courseName": "Supply Chain Management - Global" },
{ "courseName": "Sustainable Business Management" },
{ "courseName": "Sustainable Waste Management" },
{ "courseName": "Technical Communication" },
{ "courseName": "Tourism - Destinations and Travel Management" },
{ "courseName": "Urban Planning and GIS" },
{ "courseName": "Technical Systems Analysis" },
{ "courseName": "Virtual Reality Production" },
{ "courseName": "Virtualization and Cloud Computing" },
{ "courseName": "Visual Merchandising Arts" },
{ "courseName": "Web Development and Internet Applications Fundamentals" },
{ "courseName": "Welding Engineering Technician - Robotics" },
{ "courseName": "Welding Engineering Technician - Inspection" },
{ "courseName": "Welding and Fabrication Technician" },
{ "courseName": "Wireless Network Infrastructure" },
{ "courseName": "Woodworking Technician" },
{ "courseName": "Community Pharmacy Assistant" },
{ "courseName": "Network Technical Support" },
{ "courseName": "Real Estate Development and Management" },
{ "courseName": "Advertising and Marketing Communications (AMC) Kingston" },
{ "courseName": "Bachelor of Business Administration (BBA) Kingston" },
{ "courseName": "Bachelor of Science (Nursing) Brockville" },
{ "courseName": "Bachelor of Science (Nursing) Cornwall" },
{ "courseName": "Biotechnology Advanced Kingston" },
{ "courseName": "Business Kingston" },
{ "courseName": "Business Brockville" },
{ "courseName": "Business Cornwall" },
{ "courseName": "Business Accounting Kingston" },
{ "courseName": "Business Accounting Cornwall" },
{ "courseName": "Business Administration - Cornwall" },
{ "courseName": "Business Administration - Accounting Kingston" },
{ "courseName": "Pre-Health Science Pathway to Advanced Diplomas and Degrees (Cornwall)" },
{ "courseName": "Business Administration - Human Resources Kingston" },
{ "courseName": "Business Administration Marketing Kingston" },
{ "courseName": "Business Analytics - Academic and Professional Success in Canada Kingston" },
{ "courseName": "Business Human Resources" },
{ "courseName": "Business Marketing Kingston" },
{ "courseName": "Child and Youth Care Kingston" },
{ "courseName": "Civil Engineering Technology Kingston" },
{ "courseName": "Computer Programming Cornwall" },
{ "courseName": "Computer Programming and Analysis Kingston" },
{ "courseName": "Computer Systems Technician Kingston" },
{ "courseName": "Computer Systems Technician Cornwall" },
{ "courseName": "Culinary Management Kingston" },
{ "courseName": "Cybersecurity Kingston" },
{ "courseName": "Digital Marketing Communications (DMC) Kingston" },
{ "courseName": "Electrical Engineering Technician (Kingston)" },
{ "courseName": "Early Childhood Education Kingston" },
{ "courseName": "Early Childhood Education Cornwall" },
{ "courseName": "Energy Systems Engineering Technician Kingston" },
{ "courseName": "Fitness and Health Promotion Kingston" },
{ "courseName": "Game Programming Cornwall" },
{ "courseName": "General Arts & Science Kingston" },
{ "courseName": "General Arts & Science General Stream Cornwall" },
{ "courseName": "General Arts & Science Cornwall" },
{ "courseName": "Graphic Design Kingston" },
{ "courseName": "Hairstyling (Accelerated) Kingston" },
{ "courseName": "Health Information Management Kingston" },
{ "courseName": "Hospitality Kingston" },
{ "courseName": "Human Resource Management Kingston" },
{ "courseName": "Health Care Administration Kingston" },
{ "courseName": "Instrumentation and Control Engineering Technology Cornwall" },
{ "courseName": "Instrumentation and Control Engineering Technology Kingston" },
{ "courseName": "Law Clerk Kingston" },
{ "courseName": "Mechanical Technician Kingston" },
{ "courseName": "Mental Wellness and Addictions Worker Brockville" },
{ "courseName": "Music & Digital Media Kingston" },
{ "courseName": "Music Theatre - Performance Brockville" },
{ "courseName": "Office Administration Health Services Kingston" },
{ "courseName": "Office Administration Legal Kingston" },
{ "courseName": "Office Administration Health Services Brockville" },
{ "courseName": "Personal Support Worker Brockville" },
{ "courseName": "Police Foundations Cornwall" },
{ "courseName": "Project Management Kingston" },
{ "courseName": "Project Management Cornwall" },
{ "courseName": "Social Service Worker Cornwall" },
{ "courseName": "Supply Chain Management Cornwall" },
{ "courseName": "Therapeutic Recreation Kingston" },
{ "courseName": "Tourism Kingston" },
{ "courseName": "User Experience Design (UX Design) Kingston" },
{ "courseName": "Wind Turbine Technician Kingston" },
{ "courseName": "Visual & Creative Arts - Fine Arts Brockville" },
{ "courseName": "Bachelor of Business Administration (BBA)" },
{ "courseName": "Master of Business Administration (MBA)" },
{ "courseName": "Bachelor of Commerce (B.Com)" },
{ "courseName": "Master of Commerce (M.Com)" },
{ "courseName": "Bachelor of Finance" },
{ "courseName": "Master of Finance (MFin)" },
{ "courseName": "Bachelor of Accounting" },
{ "courseName": "Master of Accounting (MAcc)" },
{ "courseName": "Bachelor of Marketing" },
{ "courseName": "Master of Marketing (MMktg)" },
{ "courseName": "Bachelor of International Business" },
{ "courseName": "Master of International Business" },
{ "courseName": "Bachelor of Entrepreneurship" },
{ "courseName": "Master of Entrepreneurship" },
{ "courseName": "Bachelor of Human Resource Management" },
{ "courseName": "Master of Human Resource Management" },
{ "courseName": "Bachelor of Supply Chain Management" },
{ "courseName": "Master of Supply Chain Management" },
{ "courseName": "Bachelor of Economics" },
{ "courseName": "Master of Economics" },
{ "courseName": "Bachelor of Business Analytics" },
{ "courseName": "Master of Business Analytics" },
{ "courseName": "Bachelor of Operations Management" },
{ "courseName": "Master of Operations Management" },
{ "courseName": "Bachelor of Event Management" },
{ "courseName": "Master of Event Management" },
{ "courseName": "Bachelor of Retail Management" },
{ "courseName": "Master of Retail Management" },
{ "courseName": "Bachelor of Hospitality Management" },
{ "courseName": "Master of Hospitality Management" },
{ "courseName": "Bachelor of Mechanical Engineering (B.Eng)" },
{ "courseName": "Master of Mechanical Engineering (M.Eng)" },
{ "courseName": "Bachelor of Civil Engineering" },
{ "courseName": "Master of Civil Engineering" },
{ "courseName": "Bachelor of Electrical Engineering" },
{ "courseName": "Master of Electrical Engineering" },
{ "courseName": "Bachelor of Computer Engineering" },
{ "courseName": "Master of Computer Engineering" },
{ "courseName": "Bachelor of Aerospace Engineering" },
{ "courseName": "Master of Aerospace Engineering" },
{ "courseName": "Bachelor of Biomedical Engineering" },
{ "courseName": "Master of Biomedical Engineering" },
{ "courseName": "Bachelor of Chemical Engineering" },
{ "courseName": "Master of Chemical Engineering" },
{ "courseName": "Bachelor of Environmental Engineering" },
{ "courseName": "Master of Environmental Engineering" },
{ "courseName": "Bachelor of Industrial Engineering" },
{ "courseName": "Master of Industrial Engineering" },
{ "courseName": "Bachelor of Robotics Engineering" },
{ "courseName": "Master of Robotics Engineering" },
{ "courseName": "Bachelor of Telecommunications Engineering" },
{ "courseName": "Master of Telecommunications Engineering" },
{ "courseName": "Bachelor of Petroleum Engineering" },
{ "courseName": "Master of Petroleum Engineering" },
{ "courseName": "Bachelor of Marine Engineering" },
{ "courseName": "Master of Marine Engineering" },
{ "courseName": "Bachelor of Mechatronics Engineering" },
{ "courseName": "Master of Mechatronics Engineering" },
{ "courseName": "Bachelor of Software Engineering" },
{ "courseName": "Master of Software Engineering" },
{ "courseName": "Bachelor of Nursing (B.Nurs)" },
{ "courseName": "Master of Nursing (MSN)" },
{ "courseName": "Bachelor of Medicine (MBBS)" },
{ "courseName": "Doctor of Medicine (MD)" },
{ "courseName": "Bachelor of Pharmacy (B.Pharm)" },
{ "courseName": "Master of Pharmacy (MPharm)" },
{ "courseName": "Bachelor of Public Health (BPH)" },
{ "courseName": "Master of Public Health (MPH)" },
{ "courseName": "Bachelor of Physiotherapy (BPT)" },
{ "courseName": "Master of Physiotherapy (MPT)" },
{ "courseName": "Bachelor of Occupational Therapy" },
{ "courseName": "Master of Occupational Therapy" },
{ "courseName": "Bachelor of Dentistry (BDS)" },
{ "courseName": "Master of Dentistry" },
{ "courseName": "Bachelor of Biomedical Science" },
{ "courseName": "Master of Biomedical Science" },
{ "courseName": "Bachelor of Radiology" },
{ "courseName": "Master of Radiology" },
{ "courseName": "Bachelor of Optometry" },
{ "courseName": "Master of Optometry" },
{ "courseName": "Bachelor of Veterinary Science (BVSc)" },
{ "courseName": "Master of Veterinary Science" },
{ "courseName": "Bachelor of Clinical Psychology" },
{ "courseName": "Master of Clinical Psychology" },
{ "courseName": "Bachelor of Nutrition and Dietetics" },
{ "courseName": "Master of Nutrition and Dietetics" },
{ "courseName": "Bachelor of Speech-Language Pathology" },
{ "courseName": "Master of Speech-Language Pathology" },
{ "courseName": "Bachelor of Genetic Counseling" },
{ "courseName": "Master of Genetic Counseling" },
{ "courseName": "Bachelor of Health Administration" },
{ "courseName": "Master of Health Administration" },
{ "courseName": "Bachelor of Health Sciences" },
{ "courseName": "Master of Health Sciences" },
{ "courseName": "Bachelor of Emergency Management" },
{ "courseName": "Master of Emergency Management" },
{ "courseName": "Bachelor of Computer Science (BSc CS)" },
{ "courseName": "Master of Computer Science (MSc CS)" },
{ "courseName": "Bachelor of Information Technology (B.IT)" },
{ "courseName": "Master of Information Technology (M.IT)" },
{ "courseName": "Bachelor of Software Engineering" },
{ "courseName": "Master of Software Engineering" },
{ "courseName": "Bachelor of Data Science" },
{ "courseName": "Master of Data Science" },
{ "courseName": "Bachelor of Artificial Intelligence" },
{ "courseName": "Master of Artificial Intelligence" },
{ "courseName": "Bachelor of Cybersecurity" },
{ "courseName": "Master of Cybersecurity" },
{ "courseName": "Bachelor of Network Engineering" },
{ "courseName": "Master of Network Engineering" },
{ "courseName": "Bachelor of Information Systems" },
{ "courseName": "Master of Information Systems" },
{ "courseName": "Bachelor of Cloud Computing" },
{ "courseName": "Master of Cloud Computing" },
{ "courseName": "Bachelor of Web Development" },
{ "courseName": "Master of Web Development" },
{ "courseName": "Bachelor of Mobile App Development" },
{ "courseName": "Master of Mobile App Development" },
{ "courseName": "Bachelor of Game Design" },
{ "courseName": "Master of Game Design" },
{ "courseName": "Bachelor of Information Security" },
{ "courseName": "Master of Information Security" },
{ "courseName": "Bachelor of Digital Media" },
{ "courseName": "Master of Digital Media" },
{ "courseName": "Bachelor of Computer Graphics" },
{ "courseName": "Master of Computer Graphics" },
{ "courseName": "Bachelor of Human-Computer Interaction" },
{ "courseName": "Master of Human-Computer Interaction" },
{ "courseName": "Bachelor of IT Management" },
{ "courseName": "Master of IT Management" },
{ "courseName": "Bachelor of Arts (BA)" },
{ "courseName": "Master of Arts (MA)" },
{ "courseName": "Bachelor of Fine Arts (BFA)" },
{ "courseName": "Master of Fine Arts (MFA)" },
{ "courseName": "Bachelor of English Literature" },
{ "courseName": "Master of English Literature" },
{ "courseName": "Bachelor of History" },
{ "courseName": "Master of History" },
{ "courseName": "Bachelor of Philosophy" },
{ "courseName": "Master of Philosophy" },
{ "courseName": "Bachelor of Sociology" },
{ "courseName": "Master of Sociology" },
{ "courseName": "Bachelor of Anthropology" },
{ "courseName": "Master of Anthropology" },
{ "courseName": "Bachelor of Political Science" },
{ "courseName": "Master of Political Science" },
{ "courseName": "Bachelor of Psychology" },
{ "courseName": "Master of Psychology" },
{ "courseName": "Bachelor of International Relations" },
{ "courseName": "Master of International Relations" },
{ "courseName": "Bachelor of Geography" },
{ "courseName": "Master of Geography" },
{ "courseName": "Bachelor of Economics" },
{ "courseName": "Master of Economics" },
{ "courseName": "Bachelor of Gender Studies" },
{ "courseName": "Master of Gender Studies" },
{ "courseName": "Bachelor of Criminology" },
{ "courseName": "Master of Criminology" },
{ "courseName": "Bachelor of Cultural Studies" },
{ "courseName": "Master of Cultural Studies" },
{ "courseName": "Bachelor of Communication" },
{ "courseName": "Master of Communication" },
{ "courseName": "Bachelor of Media Studies" },
{ "courseName": "Master of Media Studies" },
{ "courseName": "Bachelor of Journalism" },
{ "courseName": "Master of Journalism" },
{ "courseName": "Bachelor of Graphic Design" },
{ "courseName": "Master of Graphic Design" },
{ "courseName": "Bachelor of Performing Arts" },
{ "courseName": "Master of Performing Arts" },
{ "courseName": "Bachelor of Science (B.Sc)" },
{ "courseName": "Master of Science (M.Sc)" },
{ "courseName": "Bachelor of Physics" },
{ "courseName": "Master of Physics" },
{ "courseName": "Bachelor of Chemistry" },
{ "courseName": "Master of Chemistry" },
{ "courseName": "Bachelor of Biology" },
{ "courseName": "Master of Biology" },
{ "courseName": "Bachelor of Environmental Science" },
{ "courseName": "Master of Environmental Science" },
{ "courseName": "Bachelor of Geology" },
{ "courseName": "Master of Geology" },
{ "courseName": "Bachelor of Biochemistry" },
{ "courseName": "Master of Biochemistry" },
{ "courseName": "Bachelor of Microbiology" },
{ "courseName": "Master of Microbiology" },
{ "courseName": "Bachelor of Biotechnology" },
{ "courseName": "Master of Biotechnology" },
{ "courseName": "Bachelor of Genetics" },
{ "courseName": "Master of Genetics" },
{ "courseName": "Bachelor of Zoology" },
{ "courseName": "Master of Zoology" },
{ "courseName": "Bachelor of Botany" },
{ "courseName": "Master of Botany" },
{ "courseName": "Bachelor of Marine Biology" },
{ "courseName": "Master of Marine Biology" },
{ "courseName": "Bachelor of Ecology" },
{ "courseName": "Master of Ecology" },
{ "courseName": "Bachelor of Environmental Management" },
{ "courseName": "Master of Environmental Management" },
{ "courseName": "Bachelor of Laws (LLB)" },
{ "courseName": "Master of Laws (LLM)" },
{ "courseName": "Bachelor of Criminal Law" },
{ "courseName": "Master of Criminal Law" },
{ "courseName": "Bachelor of International Law" },
{ "courseName": "Master of International Law" },
{ "courseName": "Bachelor of Corporate Law" },
{ "courseName": "Master of Corporate Law" },
{ "courseName": "Bachelor of Human Rights Law" },
{ "courseName": "Master of Human Rights Law" },
{ "courseName": "Bachelor of Intellectual Property Law" },
{ "courseName": "Master of Intellectual Property Law" },
{ "courseName": "Bachelor of Taxation Law" },
{ "courseName": "Master of Taxation Law" },
{ "courseName": "Bachelor of Environmental Law" },
{ "courseName": "Master of Environmental Law" },
{ "courseName": "Bachelor of Labor Law" },
{ "courseName": "Master of Labor Law" },
{ "courseName": "Bachelor of Family Law" },
{ "courseName": "Master of Family Law" },
{ "courseName": "Bachelor of Immigration Law" },
{ "courseName": "Master of Immigration Law" },
{ "courseName": "Bachelor of Sports Law" },
{ "courseName": "Master of Sports Law" },
{ "courseName": "Bachelor of Maritime Law" },
{ "courseName": "Master of Maritime Law" },
{ "courseName": "Bachelor of Arbitration Law" },
{ "courseName": "Master of Arbitration Law" },
{ "courseName": "Bachelor of Civil Litigation" },
{ "courseName": "Master of Civil Litigation" },
{ "courseName": "Bachelor of Education (B.Ed)" },
{ "courseName": "Master of Education (M.Ed)" },
{ "courseName": "Bachelor of Early Childhood Education" },
{ "courseName": "Master of Early Childhood Education" },
{ "courseName": "Bachelor of Primary Education" },
{ "courseName": "Master of Primary Education" },
{ "courseName": "Bachelor of Secondary Education" },
{ "courseName": "Master of Secondary Education" },
{ "courseName": "Bachelor of Special Education" },
{ "courseName": "Master of Special Education" },
{ "courseName": "Bachelor of Educational Psychology" },
{ "courseName": "Master of Educational Psychology" },
{ "courseName": "Bachelor of Curriculum and Instruction" },
{ "courseName": "Master of Curriculum and Instruction" },
{ "courseName": "Bachelor of Educational Leadership" },
{ "courseName": "Master of Educational Leadership" },
{ "courseName": "Bachelor of Adult Education" },
{ "courseName": "Master of Adult Education" },
{ "courseName": "Bachelor of TESOL" },
{ "courseName": "Master of TESOL" },
{ "courseName": "Bachelor of Instructional Design" },
{ "courseName": "Master of Instructional Design" },
{ "courseName": "Bachelor of Literacy Education" },
{ "courseName": "Master of Literacy Education" },
{ "courseName": "Bachelor of Education Policy" },
{ "courseName": "Master of Education Policy" },
{ "courseName": "Bachelor of STEM Education" },
{ "courseName": "Master of STEM Education" },
{ "courseName": "Bachelor of Architecture (B.Arch)" },
{ "courseName": "Master of Architecture (M.Arch)" },
{ "courseName": "Bachelor of Interior Design" },
{ "courseName": "Master of Interior Design" },
{ "courseName": "Bachelor of Landscape Architecture" },
{ "courseName": "Master of Landscape Architecture" }
  ]
  
  